
[package]
name = "ipc"
version = "0.1.0"
edition = "2024"

[dependencies]
bytemuck = "1.25.0"

[target.'cfg(loom)'.dependencies]
loom = "0.7.2"

[dev-dependencies]
benchkit = { path = "../benchkit", features = ["alloc"] }
telemetry = { path = "../telemetry", features = ["histogram"] }
core_affinity = "0.8"
dhat = "0.3"

[[bench]]
name = "self_latency"
harness = false

[[bench]]
name = "cross_core"
harness = false

[lints.rust]
unexpected_cfgs  = {level = "warn", check-cfg = ['cfg(loom)']}