
[package]
name = "orderbook"
version = "0.1.0"
edition = "2024"

[dependencies]
types = {path = "../types"}
arena = {path = "../arena"}
rustc-hash = "2.1.2"
bytemuck = "1.25.0"

[dev-dependencies]
proptest = "1"
telemetry = {path = "../telemetry", features = ["histogram"]}
benchkit = {path = "../benchkit"}

[[bench]]
name = "orderbook_bench"
harness = false

