[package]
name = "arena"
version = "0.1.0"
edition = "2024"


[dependencies]
types = {path = "../types"}
bytemuck = "1.25.0"

[dev-dependencies]
telemetry = {path = "../telemetry", features = ["primitives-only", "histogram"]}
benchkit = {path = "../benchkit"}

[[bench]]
name = "arena_bench"
harness = false

