[package]
name = "arena"
version = "0.1.0"
edition = "2024"


[dependencies]
types = {path = "../types"}

[dev-dependencies]
criterion = {version = "0.8.2", features = ["html_reports"]}
telemetry = {path = "../telemetry", features = ["primitives-only", "histogram"]}

[[bench]]
name = "arena_bench"
harness = false

